# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: playground

  # A short description of the repository that will show up on GitHub
  description: this is just a testsuite for all the experimental stuff, before implement it in real life repos

  # A URL with more information about the repository
  # homepage: https://github.com/Just-Another-Weather-Site
