name: Auto approve

on:
  pull_request_target:
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.4.0
        if: github.actor == 'renovate[bot]'