# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Unit Test with Coverage Reports

on: [push]

jobs:
    run:
        name: "Test Coverage"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ["8.2"]

        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

            - name: Install PHP
              uses: shivammathur/setup-php@2.26.0
              with:
                  php-version: ${{ matrix.php-versions }}
                  coverage: xdebug
                  extensions: gd,mbstring
                  tools: phpunit

            - name: Install dependencies
              uses: ramsey/composer-install@2.2.0

            - name: Autoloader
              run: composer dump-autoload

            - name: Run PHPUnit
              run: vendor/bin/phpunit --coverage-text --coverage-clover coverage.xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3.1.4

            - name: Upload coverage to Codacy
              uses: codacy/codacy-coverage-reporter-action@v1.3.0
              with:
                project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}  
                coverage-reports: coverage.xml