name: CI-coverage

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0

      - uses: php-actions/composer@v6.0.0
        with:
          command: dump-autoload

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3.0.0
        with:
          bootstrap: vendor/autoload.php