name: Validate Composer files

on: [push]

jobs:
  validate_composer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Cache Composer dependencies
        uses: actions/cache@v3.3.2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Validate dependencies
        uses: php-actions/composer@v6.1.1
        with:
          command: validate
          php_version: "8.2.0"