name: Validate Composer files

on: [push]

jobs:
  validate_composer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Cache Composer dependencies
        uses: actions/cache@v3.0.11
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Validate dependencies
        uses: php-actions/composer@v6.0.0
        with:
          command: validate
          php_version: "8.0.1"